services:
  grafana:
    container_name: blinkit-grafana
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin123
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - grafana-storage:/var/lib/grafana
    - ./monitoring/grafana-dashboard.json:/var/lib/grafana/dashboards/blinkit.json
  loki:
    command: -config.file=/etc/loki/local-config.yaml
    container_name: blinkit-loki
    image: grafana/loki:latest
    ports:
    - 3100:3100
    restart: unless-stopped
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --storage.tsdb.retention.time=200h
    - --web.enable-lifecycle
    container_name: blinkit-prometheus
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  promtail:
    command: -config.file=/etc/promtail/config.yml
    container_name: blinkit-promtail
    image: grafana/promtail:latest
    restart: unless-stopped
    volumes:
    - ./logs:/var/log/blinkit
    - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
version: '3.8'
volumes:
  grafana-storage: {}
