clients:
- url: http://loki:3100/loki/api/v1/push
positions:
  filename: /tmp/positions.yaml
scrape_configs:
- job_name: blinkit-logs
  pipeline_stages:
  - json:
      expressions:
        level: level
        message: message
        request_id: request_id
        service: service_name
        timestamp: timestamp
  - labels:
      level: ''
      request_id: ''
      service: ''
  static_configs:
  - labels:
      __path__: /var/log/blinkit/*.log
      job: blinkit-logs
    targets:
    - localhost
server:
  grpc_listen_port: 0
  http_listen_port: 9080
